### Inicializando las librerias a ocupar ###

In [5]:
import pyarrow.parquet as pq
import gcsfs
import pandas as pd
from pandas_gbq import to_gbq
import bigframes.pandas as bpd
import json
from google.cloud import storage

### Librerias a instalar ###

In [6]:
#pip install bigframes
#pip install pandas-gbq
#pip install google-cloud-bigquery
#pip install  --upgrade bigframes

### Información BIG QUERY

In [7]:
PROJECT_ID = 'adsac-455509'
LOCATION = "southamerica-east1"

### insertando opciones de BigQuery DataFrames

In [8]:
bpd.options.bigquery.project = PROJECT_ID
bpd.options.bigquery.location = LOCATION
bpd.options.display.progress_bar = None

#### Para leer la tabla Business curada en big query

In [9]:
#This is how you read a BigQuery table
df_business_curated = bpd.read_gbq("adsac-455509.Curated.Business")
df_business_curated.peek()

C:\Users\DELIA MONTOYA\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py:3577: UserWarning: Reading cached table from 2025-04-02 22:19:04.012777+00:00 to avoid
incompatibilies with previous reads of this table. To read the latest
version, set `use_cache=False` or close the current session with
Session.close() or bigframes.pandas.close_session().
  exec(code_obj, self.user_global_ns, self.user_ns)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
594,wlRUC49YirsCBdv7wa3cmg,Min Moon,4800 Chef Menteur Hwy,New Orleans,TN,70126,30.005572,-90.032872,3.5,13,0,"{'Alcohol': ""u'none'"", 'WiFi': ""u'no'"", 'Noise...","Chinese, Restaurants",None
523,niGe9qqepMcewft8_g_zgA,"The Biergarten, St. Louis",12TH And Lynch St,Saint Louis,LA,63118,38.598985,-90.214239,3.5,154,1,"{'BikeParking': 'True', 'OutdoorSeating': 'Tru...","Nightlife, Beer Gardens, Breweries, American (...","{'Monday': '0:0-0:0', 'Tuesday': '11:0-18:0', ..."
358,avcD0BzvfPo2HW0t7chdZg,Target Optical,1225 W Irvington Rd,Tucson,MO,85714,32.160372,-110.990237,4.5,7,1,"{'BusinessParking': ""{'garage': False, 'street...","Optometrists, Health & Medical, Shopping, Eyew...","{'Monday': '10:0-20:0', 'Tuesday': '10:0-20:0'..."
416,nbOceaVJAFoyyaF-N3wTpw,Lamp & Shade Outlet,8601 Torresdale Ave,Philadelphia,ID,19136,40.042755,-75.010275,4.5,11,1,None,"Home Services, Lighting Fixtures & Equipment","{'Monday': '10:0-17:0', 'Tuesday': '10:0-17:0'..."
36,RmDn5oeB_HABKHrEx3F2HA,Crescent City Cigar Shop,730 Orleans Ave,New Orleans,NJ,70116,29.958791,-90.065062,4.5,49,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Lounges, Nightlife, Cigar Bars, Shopping, Toba...","{'Monday': '12:0-22:0', 'Tuesday': '12:0-22:0'..."

#### Para leer la tabla User curada en big query

In [10]:
# This is how you read a BigQuery table
df_user_curated = bpd.read_gbq("adsac-455509.Curated.Usuario")
df_user_curated.peek()

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,average_stars
499224,MRassD-e0Y5hISKBvwKB9g,Brittney,9,2019-04-06 17:16:07,4,0,2,,"NimgVsvvpboEDnPk1XYrqA, sjwEKZmVEqx7NEaOthpiwg...",0,4.8
498946,Km-oFDgcsQ2L3MA70PreYw,Mike,2,2018-10-06 16:35:12,0,0,0,,"kwLw82Q32PXaPIkcpiuwGA, PxxN3up621SzP5fNQYZdow...",0,5.0
499185,4NCCnQVkQJSQDES1qH1WSQ,Leonard,4,2019-09-22 01:01:03,3,3,1,,None,0,1.7
499062,yXKS8f6XoyMtuW6pvcFgwg,Lorenzo,17,2012-06-30 15:11:33,34,26,3,,"sld1mcOTbanS73LIpfbmGw, IKki4Ayak4pQn-90Pmef9w...",0,2.5
498917,cR5bvpc0xeQpm-Bsx67A8w,Meg,270,2010-01-16 21:00:09,525,149,186,"2012,2013,2014,2015,2016,2017,2018","AzKNHxUdKgWACYkQk9zFsw, ASCGYpPvcJvo-c8rn8BHoQ...",15,3.58

#### Leer tabla Checkin curada en big query

In [11]:
#This is how you read a BigQuery table
df_checkin_pandas = bpd.read_gbq("adsac-455509.Curated.CheckIn")
df_checkin_pandas.peek()

                                                  date             business_id
6    2016-08-10 20:37:57, 2016-09-15 22:34:05, 2016...  cmGXUEe6GsjI0HI84yogrg
636                                2012-04-07 19:02:44  1LoKM5J-w77CXL4jbdF2eA
282  2010-12-31 03:02:28, 2011-05-03 00:18:32, 2012...  Nu8jVC-HJykak3aqhPAHBQ
474  2015-05-16 22:54:54, 2015-08-08 19:39:44, 2015...  h0vlYNJe3V31AtZOAEyAig
109  2012-06-10 12:37:57, 2012-06-12 01:31:13, 2012...  abQpaUX09LiT8GQBWJR99A

#### Obtener tabla Review Curada en big query

In [12]:
#This is how you read a BigQuery table
df_checkin_pandas = bpd.read_gbq("adsac-455509.Curated.Review")
df_checkin_pandas.peek()

,text,stars,date,review_id,business_id,user_id
1066123,"Atmosphere was cool, I love the building and d...",2.0,2016-02-02 17:48:15+00:00,5NPQUo_U2vvL7WlYcFdl6w,VAeEXLbEcI9Emt9KGYq9aA,EoXBUkyu7JXFiaSGEwnvew
1065497,I seriously think they put crack in the Cane's...,4.0,2010-05-26 19:34:55+00:00,wtxiZNyvUV0eC3h5N9wCLA,7z_CcZ_wE2c-qPs51HU7TA,dTYO6-81GrNZbILGxNKI6A
1065876,I had an amazing experience shopping here! I w...,5.0,2021-01-25 03:22:33+00:00,XojfL-pfkMOLYnSODnMB9Q,O8Tvu3WLJUohr8FmBVckhg,naTlKv7PYHc0bFOwbqUd4Q
1065870,"Was visiting Clearwater Beach, FL and the muss...",5.0,2017-04-25 21:48:19+00:00,W1iR8ey0g9JeGofSELggmw,x3Ifr1jj2Qu7JDZto6Kbfg,Sdox8cB7z7zQdYMbb6kxIw
1065426,On referral we hired Emma as our day of weddin...,5.0,2014-08-02 17:38:01+00:00,AfUt9JCgtqI_e0s1Pi6sVQ,B0Lm1QztjkI3TBd3RShAMw,Wx5WoxawFPfNae-ACl1Y0A